### PR TITLE
add natbib package, add doi package (incl example)

### PR DESCRIPTION
**Pull request by da5nsy**
In response to https://github.com/kourgeorge/arxiv-style/issues/12:
- Added natbib package
- Added doi package (and example)
- Rewritten parts of the example tex file for clarity

### CODE REVIEW

**Comment by gokhanercan** [comment]
Correct me if I'm wrong but I see that this update fixes citep{} and citet{} usages but also changes default citation style from "[2]" to "Kour and Saabne [2014b]" for default **\cite{}** usage. It cancels the default numbered referencing fashion [1][2].

**Comment by da5nsy** [comment]
That is correct

**Review by szrlee — APPROVED** [review]
Correct

**Review by kourgeorge — APPROVED** [review]

**Comment by kourgeorge** [comment]
Thank you @da5nsy @gokhanercan @szrlee for the effort.

**Pull request merged**
